apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-yaml-config
data:
  prometheus.yaml:  |
{{ if eq .Values.prometheusConfigType "Simple" }}
    scrape_configs:
      - job_name: {{ .Values.prometheus.job_name }}
        scrape_interval: {{ .Values.prometheus.scrape_interval }}
        scrape_timeout: {{ .Values.prometheus.scrape_timeout }}
        static_configs:
        - targets:
{{ .Values.prometheus.targets | toYaml | indent 10 }}
{{ else if eq .Values.prometheusConfigType "File" }}
{{ .Files.Get "prometheus.yml" | indent 4 }}
{{ else }}
{{ .Values.prometheusValues | toYaml | indent 4 }}
{{ end }}